from numpy import nan

MOLEXCLUDED = ['W', 'NA', 'CL', 'ION']
RESEXCLUDED = ['W', 'ION']

LIPIDDEF = {
    # Phosphatidylcholine
    'PC':[
        'DTPC',
        'DLPC',
        'DPPC',
        'DBPC',
        'DXPC',
        'DYPC',
        'DVPC',
        'DOPC',
        'DIPC',
        'DFPC',
        'DGPC',
        'DAPC',
        'DRPC',
        'DNPC',
        'LPPC',
        'POPC',
        'PGPC',
        'PEPC',
        'PIPC',
        'PAPC',
        'PUPC',
        'PRPC',
        'POPX',
        'PIPX',
    ],

    # Phosphatidylethanolamine
    'PE':[
        'DTPE',
        'DLPE',
        'DPPE',
        'DBPE',
        'DXPE',
        'DYPE',
        'DVPE',
        'DOPE',
        'DIPE',
        'DFPE',
        'DGPE',
        'DAPE',
        'DUPE',
        'DRPE',
        'DNPE',
        'LPPE',
        'POPE',
        'PGPE',
        'PQPE',
        'PIPE',
        'PAPE',
        'PUPE',
        'PRPE',
    ],

    # Phosphatidylserine
    'PS':[
        'DTPS',
        'DLPS',
        'DPPS',
        'DBPS',
        'DXPS',
        'DYPS',
        'DVPS',
        'DOPS',
        'DIPS',
        'DFPS',
        'DGPS',
        'DAPS',
        'DUPS',
        'DRPS',
        'DNPS',
        'LPPS',
        'POPS',
        'PGPS',
        'PQPS',
        'PIPS',
        'PAPS',
        'PUPS',
        'PRPS',
    ],

    #Phosphatidylglycerol
    'PG':[
        'DTPG',
        'DLPG',
        'DPPG',
        'DBPG',
        'DXPG',
        'DYPG',
        'DVPG',
        'DOPG',
        'DIPG',
        'DFPG',
        'DGPG',
        'DAPG',
        'DRPG',
        'DNPG',
        'LPPG',
        'POPG',
        'PGPG',
        'PIPG',
        'PAPG',
        'PRPG',
        'OPPG',
        'JPPG',
        'JFPG',
    ],

    # Phosphatidic acid
    'PA':[
        'DTPA',
        'DLPA',
        'DPPA',
        'DBPA',
        'DXPA',
        'DYPA',
        'DVPA',
        'DOPA',
        'DIPA',
        'DFPA',
        'DGPA',
        'DAPA',
        'DRPA',
        'DNPA',
        'LPPA',
        'POPA',
        'PGPA',
        'PIPA',
        'PAPA',
        'PUPA',
        'PRPA',
    ],

    # phosphatidylinositol
    'PI':[
        'DPPI',
        'PVPI',
        'POPI',
        'PIPI',
        'PAPI',
        'PUPI',
    ],

    'PIPs':[
        'DPP1',
        'PVP1',
        'POP1',
        'DPP2',
        'PVP2',
        'POP2',
        'PVP3',
        'POP3',
    ],

    # Diacylglycerol
    'DAG':[
        'PVDG',
        'PODG',
        'PIDG',
        'PADG',
        'PUDG',
        'TOG',
    ],

    # Lysophosphatidylcholine
    'LPC':[
        'CPC',
        'TPC',
        'LPC',
        'PPC',
        'VPC',
        'OPC',
        'IPC',
        'APC',
        'UPC',
    ],

    # Sphingomyelin
    'SM':[
        'DPSM',
        'DBSM',
        'DXSM',
        'PVSM',
        'POSM',
        'PGSM',
        'PNSM',
        'BNSM',
        'XNSM',
    ],

    # Ceramide
    'CER':[
        'DPCE',
        'DXCE',
        'PNCE',
        'XNCE',
    ],

    # Glycosphingolipids
    'GS':[
        'DPGS',
    ],

    # monosialotetrahexosylganglioside & monosialodihexosylganglioside 
    'GM1':[
        'DPG1',
        'DBG1',
        'DXG1',
        'PNG1',
        'XNG1',],

    'GM3':[
        'DPG3',
        'DBG3',
        'DXG3',
        'PNG3',
        'XNG3',
    ],

    # Glycoglycerolipids
    'DG':[
        'DPMG',
        'OPMG',
        'DFMG',
        'FPMG',
        'DPSG',
        'OPSG',
        'FPSG',
        'DPGG',
        'OPGG',
        'DFGG',
        'FPGG',
    ],

    # Sterols
    'Sterols':[
        'CHOL',
        'CHOA',
        'CHYO',
        'ERGO',
        'HBHT',
        'HDPT',
        'HHOP',
        'HOPR',
    ],

    # Fatty acids
    'FA':[
        'LCA',
        'PCA',
        'BCA',
        'XCA',
        'ACA',
        'UCA',
    ]
}

NAME2TYPE = {}
for key in LIPIDDEF:
    for name in LIPIDDEF[key]:
        #lipidType.append(key)
        #lipidName.append(name)
        NAME2TYPE[name] = key

UNSATURATED = [
    'POPX',
    'DOPC',
    'PIPX',
    'PEPC',
    'PAPC',
    'DAPC',
    'PUPC',
    'POPE',
    'DOPE',
    'PIPE',
    'PQPE',
    'PAPE',
    'DAPE',
    'PUPE',
    'DUPE',
    'POSM',
    'PGSM',
    'PNSM',
    'BNSM',
    'XNSM',
    'PNG1',
    'XNG1',
    'PNG3',
    'XNG3',
    'PNCE',
    'XNCE',
    'PODG',
    'PIDG',
    'PADG',
    'PUDG',
    'POPC',
    'PIPC',
    'POPS',
    'PIPS',
    'PQPS',
    'PAPS',
    'DAPS',
    'PUPS',
    'DUPS',
    'POPI',
    'PIPI',
    'PAPI',
    'PUPI',
    'POPA',
    'PIPA',
    'PAPA',
    'PUPA',
    'POP1',
    'POP2',
    'POP3',
    'OPC',
    'IPC',
    'APC',
    'UPC',
]

NAME2UNSAT = {
    'DTPC': [0, 0],
    'DLPC': [0, 0],
    'DPPC': [0, 0],
    'DBPC': [0, 0],
    'DXPC': [0, 0],
    'DYPC': [1, 1],
    'DVPC': [1, 1],
    'DOPC': [1, 1],
    'DIPC': [2, 2],
    'DFPC': [3, 3],
    'DGPC': [1, 1],
    'DAPC': [4, 5],
    'DRPC': [6, 6],
    'DNPC': [1, 1],
    'LPPC': [0, 0],
    'POPC': [0, 1],
    'POPX': [0, 1],
    'PGPC': [0, 1],
    'PEPC': [0, 2],
    'PIPC': [0, 2],
    'PIPX': [0, 2],
    'PAPC': [0, 4],
    'PUPC': [0, 6],
    'PRPC': [0, 6],
    'DTPE': [0, 0],
    'DLPE': [0, 0],
    'DPPE': [0, 0],
    'DBPE': [0, 0],
    'DXPE': [0, 0],
    'DYPE': [1, 1],
    'DVPE': [1, 1],
    'DOPE': [1, 1],
    'DIPE': [2, 2],
    'DFPE': [3, 3],
    'DGPE': [1, 1],
    'DAPE': [4, 5],
    'DUPE': [5, 6],
    'DRPE': [6, 6],
    'DNPE': [1, 1],
    'LPPE': [0, 0],
    'POPE': [0, 1],
    'PGPE': [0, 1],
    'PQPE': [0, 3],
    'PIPE': [0, 2],
    'PAPE': [0, 4],
    'PUPE': [0, 6],
    'PRPE': [0, 6],
    'DTPS': [0, 0],
    'DLPS': [0, 0],
    'DPPS': [0, 0],
    'DBPS': [0, 0],
    'DXPS': [0, 0],
    'DYPS': [1, 1],
    'DVPS': [1, 1],
    'DOPS': [1, 1],
    'DIPS': [2, 2],
    'DFPS': [3, 3],
    'DGPS': [1, 1],
    'DAPS': [4, 5],
    'DUPS': [5, 6],
    'DRPS': [6, 6],
    'DNPS': [1, 1],
    'LPPS': [0, 0],
    'POPS': [0, 1],
    'PGPS': [0, 1],
    'PQPS': [0, 3],
    'PIPS': [0, 2],
    'PAPS': [0, 4],
    'PUPS': [0, 6],
    'PRPS': [0, 6],
    'DTPG': [0, 0],
    'DLPG': [0, 0],
    'DPPG': [0, 0],
    'DBPG': [0, 0],
    'DXPG': [0, 0],
    'DYPG': [1, 1],
    'DVPG': [1, 1],
    'DOPG': [1, 1],
    'DIPG': [2, 2],
    'DFPG': [3, 3],
    'DGPG': [1, 1],
    'DAPG': [4, 5],
    'DRPG': [6, 6],
    'DNPG': [1, 1],
    'LPPG': [0, 0],
    'POPG': [0, 1],
    'PGPG': [0, 1],
    'PIPG': [0, 2],
    'PAPG': [0, 4],
    'PRPG': [0, 6],
    'OPPG': [1, 0],
    'JPPG': [1, 0],
    'JFPG': [1, 3],
    'DTPA': [0, 0],
    'DLPA': [0, 0],
    'DPPA': [0, 0],
    'DBPA': [0, 0],
    'DXPA': [0, 0],
    'DYPA': [1, 1],
    'DVPA': [1, 1],
    'DOPA': [1, 1],
    'DIPA': [2, 2],
    'DFPA': [3, 3],
    'DGPA': [1, 1],
    'DAPA': [4, 5],
    'DRPA': [6, 6],
    'DNPA': [1, 1],
    'LPPA': [0, 0],
    'POPA': [0, 1],
    'PGPA': [0, 1],
    'PIPA': [0, 2],
    'PAPA': [0, 4],
    'PUPA': [0, 6],
    'PRPA': [0, 6],
    'DPPI': [0, 0],
    'PVPI': [0, 1],
    'POPI': [0, 1],
    'PIPI': [0, 2],
    'PAPI': [0, 4],
    'PUPI': [0, 6],
    'DPP1': [0, 0],
    'PVP1': [0, 1],
    'POP1': [0, 1],
    'DPP2': [0, 0],
    'PVP2': [0, 1],
    'POP2': [0, 1],
    'PVP3': [0, 1],
    'POP3': [0, 1],
    'PVDG': [0, 1],
    'PODG': [0, 1],
    'PIDG': [0, 2],
    'PADG': [0, 4],
    'PUDG': [0, 6],
    'CPC': [0, 0],
    'TPC': [0, 0],
    'LPC': [0, 0],
    'PPC': [0, 0],
    'VPC': [1, 1],
    'OPC': [1, 1],
    'IPC': [2, 2],
    'APC': [4, 5],
    'UPC': [5, 6],
    'DPSM': [1, 0],
    'DBSM': [1, 0],
    'DXSM': [1, 0],
    'PVSM': [1, 1],
    'POSM': [1, 1],
    'PGSM': [1, 1],
    'PNSM': [1, 1],
    'BNSM': [1, 1],
    'XNSM': [1, 1],
    'DPCE': [1, 0],
    'DXCE': [1, 0],
    'PNCE': [1, 1],
    'XNCE': [1, 1],
    'DPGS': [1, 0],
    'DPG1': [1, 0],
    'DBG1': [1, 0],
    'DXG1': [1, 0],
    'PNG1': [1, 1],
    'XNG1': [1, 1],
    'DPG3': [1, 0],
    'DBG3': [1, 0],
    'DXG3': [1, 0],
    'PNG3': [1, 1],
    'XNG3': [1, 1],
    'DPMG': [0, 0],
    'OPMG': [1, 0],
    'DFMG': [3],
    'FPMG': [3, 0],
    'DPSG': [0, 0],
    'OPSG': [1, 0],
    'FPSG': [3, 0],
    'DPGG': [0, 0],
    'OPGG': [1, 0],
    'DFGG': [3],
    'FPGG': [3, 0],
    'LCA': [0, 0],
    'PCA': [0, 0],
    'BCA': [0, 0],
    'XCA': [0, 0],
    'ACA': [4, 5],
    'UCA': [6],
    'DPTAP': [0, 0],
    'DOTAP': [1, 1],
    'DITAP': [1, 1],
    'CHOL': [0]
}